"""JSON / CSV / HTML serialisers for a ScanResult (Day 8)."""
from __future__ import annotations

import csv
import io
import json
from html import escape


def to_json(result) -> str:
    return json.dumps(result.to_dict(), indent=2)


def to_csv(result) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["name", "sources", "ips", "cname", "resolved", "risk", "risk_reasons"])
    for host in sorted(result.hosts.values(), key=lambda h: (-h.risk, h.name)):
        writer.writerow([
            host.name,
            ";".join(sorted(host.sources)),
            ";".join(host.ips),
            host.cname or "",
            host.resolved,
            host.risk,
            " | ".join(host.risk_reasons),
        ])
    return buf.getvalue()


def _risk_class(risk: int) -> str:
    if risk >= 60:
        return "high"
    if risk >= 30:
        return "med"
    if risk > 0:
        return "low"
    return "none"


def to_html(result) -> str:
    meta = result.meta
    risk = meta.get("risk", {})
    hygiene = risk.get("hygiene", {})
    counts = meta.get("counts", {})

    rows = []
    for host in sorted(result.hosts.values(), key=lambda h: (-h.risk, h.name)):
        cls = _risk_class(host.risk)
        rows.append(
            f"<tr class='{cls}'>"
            f"<td>{escape(host.name)}</td>"
            f"<td>{escape(', '.join(sorted(host.sources)))}</td>"
            f"<td>{escape(', '.join(host.ips) or (host.cname or '—'))}</td>"
            f"<td class='risk'>{host.risk}</td>"
            f"<td>{escape(' | '.join(host.risk_reasons) or '—')}</td>"
            f"</tr>"
        )

    hygiene_items = "".join(
        f"<li class='{'ok' if ok else 'bad'}'>{escape(label)}: "
        f"{'present' if ok else 'MISSING'}</li>"
        for label, ok in [
            ("SPF", hygiene.get("spf")),
            ("DMARC", hygiene.get("dmarc")),
            ("CAA", hygiene.get("caa")),
        ]
    )

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>Fierce-NG report — {escape(result.domain)}</title>
<style>
 body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:2rem;color:#1a1a2e;background:#fafafc}}
 h1{{margin:0}} .sub{{color:#666;margin:.2rem 0 1.4rem}}
 .cards{{display:flex;gap:1rem;flex-wrap:wrap;margin-bottom:1.5rem}}
 .card{{background:#fff;border:1px solid #e5e5ef;border-radius:10px;padding:1rem 1.2rem;min-width:130px}}
 .card b{{font-size:1.7rem;display:block}}
 ul.hygiene{{list-style:none;padding:0;display:flex;gap:1rem;flex-wrap:wrap}}
 ul.hygiene li{{padding:.3rem .7rem;border-radius:6px}}
 li.ok{{background:#e6f7ec;color:#0a7d33}} li.bad{{background:#fdeaea;color:#b00020}}
 table{{border-collapse:collapse;width:100%;background:#fff;border-radius:10px;overflow:hidden}}
 th,td{{text-align:left;padding:.5rem .7rem;border-bottom:1px solid #eee;font-size:.92rem}}
 th{{background:#1a1a2e;color:#fff}}
 tr.high{{background:#fdecec}} tr.med{{background:#fff6e6}} tr.low{{background:#f4f9f4}}
 td.risk{{font-weight:700;text-align:center}}
 footer{{margin-top:1.5rem;color:#999;font-size:.8rem}}
</style></head><body>
<h1>Fierce-NG report</h1>
<p class="sub">Target <b>{escape(result.domain)}</b> · mode {escape(result.mode)} ·
 {meta.get('duration_sec','?')}s · generated by fierce-ng</p>
<div class="cards">
 <div class="card"><b>{counts.get('hosts',0)}</b>hosts discovered</div>
 <div class="card"><b>{counts.get('resolved',0)}</b>resolved</div>
 <div class="card"><b>{risk.get('high_risk_count',0)}</b>high risk</div>
 <div class="card"><b>{'yes' if result.wildcard else 'no'}</b>wildcard DNS</div>
</div>
<h3>Email / certificate hygiene</h3>
<ul class="hygiene">{hygiene_items}</ul>
<h3>Discovered hosts ({len(result.hosts)})</h3>
<table><thead><tr><th>Name</th><th>Sources</th><th>Address</th><th>Risk</th><th>Findings</th></tr></thead>
<tbody>{''.join(rows)}</tbody></table>
<footer>⚠ Authorized testing only. Signed manifest: {escape(str(result.manifest.get('result_sha256','')[:16]))}…</footer>
</body></html>"""
